objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomerUpdate.cls
//test class for test creation when customer is updated
@istest
public class CustomerUpdate{
public static testmethod void customerupdate(){

Customer__c cus=new Customer__c();
cus.Name='SobhaSankar';
cus.Name__c='Likitha';
cus.Phone__c='5642879542';
insert cus;

Test__c test=new Test__c();
test.Name=cus.Name;
test.Name__c=cus.Name__c;
test.Phone__c=cus.Phone__c;
test.Salary__c=cus.Salary__c;
insert test;

system.assertEquals(test.Name,cus.Name);
system.assertEquals(test.Salary__c,cus.Salary__c);

cus.Name='Anusha';


update cus;
}
}