objects/invoice_statement__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <label>Invoice Total</label>
        <summarizedField>Line_item1__c.Line_Item_Total__c</summarizedField>
        <summaryForeignKey>Line_item1__c.invoice1__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>invoice statement</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>invoice1 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>invoice statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/deleterecords.cls
public class deleterecords {
public List<Wrapperclass> liwc{get;set;}
public boolean bool{get;set;}

public class Wrapperclass{
public boolean checked{get;set;}
public invoice_statement__c inv{get;set;}
public Wrapperclass(invoice_statement__c inv){
this.inv=inv;

}
}
public deleterecords(){
liwc=new List<Wrapperclass>();
List<invoice_statement__c> s=[select Name,Status__c,Invoice_Total__c from invoice_statement__c];
if(s.size()>0)
{
for(invoice_statement__c inv : s){
liwc.add(new Wrapperclass(inv));
}
} 
}
public void del(){
List<invoice_statement__c> liinvfordel = new List<invoice_statement__c>(); 
List<Wrapperclass> litemwrap = new List<Wrapperclass>();
for(Wrapperclass w:liwc)
{
if(w.checked){
liinvfordel.add(w.inv);
}
else
{
litemwrap.add(w);
}
}
if(liinvfordel.size()>0){
delete liinvfordel;
liwc=litemwrap;
}
else{
ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'select atleast one invoice to delete'));
} 
}

public void selectall(){
if(bool){
for(Wrapperclass w:liwc){
w.checked=true;
}}
else
for(Wrapperclass w:liwc){
w.checked=false;
}
}
}