objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Handoff_Attached__c</fullName>
        <label>Handoff Attached</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Top_X_Designation__c.object
<CustomObject>
    <fields>
        <fullName>Document_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Document Attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Top X Designations</relationshipLabel>
        <relationshipName>Top_X_Designations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Flow Down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hand Off</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Top X Designation</label>
    <nameField>
        <label>Top X Designation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Top X Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateHandoffAttached.cls
@isTest
public class UpdateHandoffAttached{
    static testmethod void HandoffAttached(){
        Account acc=new Account();
        acc.Name='test';
        insert acc;
        
        Opportunity opp=new opportunity();
        opp.Accountid=acc.id;
        opp.Name='Testdata';
        //Date myDate=Date.newinstance('2015,14,4');
        opp.CloseDate=system.today();
        opp.StageName='Prospecting';
        insert opp;
        
        Top_X_Designation__c t=new Top_X_Designation__c();
        t.Document_Attached__c=True;
        t.Type__c='Contract Flow Down/Hand Off';
        t.Opportunity__c=opp.id;
        insert t;
        Opportunity o1=[select Handoff_Attached__c from Opportunity where id=:opp.id];
        system.assertEquals('Yes',o1.Handoff_Attached__c);
        
        Opportunity t1=new Opportunity(id=opp.id);
        t.Document_Attached__c=False;
        t.Type__c='Contract Flow Down/Hand Off';
        t.Opportunity__c=opp.id;
        update t1;
        Opportunity o2=[select Handoff_Attached__c from Opportunity where id=:opp.id ];
        system.assertEquals('Yes',o2.Handoff_Attached__c);
        
        Opportunity o3=[select Handoff_Attached__c from Opportunity where id=:opp.id];
        system.assertEquals('Yes',o3.Handoff_Attached__c);
        
    }

}